[package]
name = "steven_gl"
version = "0.0.1"
authors = [ "Thinkofdeath <thinkofdeath@spigotmc.org>" ]
build = "build.rs"

[build-dependencies]
gl_generator = "0.4.2"
khronos_api = "1.0.0"

[dependencies]
libc = "0.2"
